<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_timeline',
		'title' => 'Timeline',
		'fields' => array (
			array (
				'key' => 'field_55effc766bf11',
				'label' => 'Timeline Events',
				'name' => 'tl_timeline_events',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'all',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_55effcc86bf12',
				'label' => 'Timeline Scale',
				'name' => 'tl_timeline_scale',
				'type' => 'select',
				'choices' => array (
					'human' => 'human',
					'cosmological' => 'cosmological',
				),
				'default_value' => 'human',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_561dfa779e0e9',
				'label' => 'Timeline Language',
				'name' => 'tl_timeline_language',
				'type' => 'select',
				'choices' => array (
					'en' => 'en',
					'be' => 'be',
					'de' => 'de',
					'es' => 'es',
					'fr' => 'fr',
					'he' => 'he',
					'it' => 'it',
					'jp' => 'jp',
					'nl' => 'nl',
					'no' => 'no',
					'pl' => 'pl',
					'sr' => 'sr',
					'sv' => 'sv',
					'zh-cn' => 'zh-cn',
					'zh-tw' => 'zh-tw',
				),
				'default_value' => 'en',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_561dfd537e7b0',
				'label' => 'Timeline External Media',
				'name' => 'tl_timeline_external_media_content',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_561dfd737e7b1',
				'label' => 'Timeline Media',
				'name' => 'tl_timeline_media',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_561dfd8a7e7b2',
				'label' => 'Timeline Media Credit',
				'name' => 'tl_timeline_media_credit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_561dfd947e7b3',
				'label' => 'Timeline Media Caption',
				'name' => 'tl_timeline_media_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'timeline',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_timeline-event',
		'title' => 'Timeline Event',
		'fields' => array (
			array (
				'key' => 'field_55eff8f168974',
				'label' => 'Media External Content',
				'name' => 'tle_media_external_content',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55eff8ff68975',
				'label' => 'Media Image',
				'name' => 'tle_media_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55eff90e68976',
				'label' => 'Media Thumbnail',
				'name' => 'tle_media_thumbnail',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55eff91e68977',
				'label' => 'Media Caption',
				'name' => 'tle_media_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55f827af7ba7f',
				'label' => 'Media Credit',
				'name' => 'tle_media_credit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55eff93068978',
				'label' => 'Start Date',
				'name' => 'tle_start_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_55eff96768979',
				'label' => 'Specify Start Time?',
				'name' => 'tle_specify_start_time',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55eff99a155ba',
				'label' => 'Start Time Hour',
				'name' => 'tle_start_hour',
				'type' => 'number',
				'instructions' => 'A number from 0-23',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff96768979',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effbdd22294',
				'label' => 'Start Time Minute',
				'name' => 'tle_start_minute',
				'type' => 'number',
				'instructions' => 'A number from 0-59',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff96768979',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55eff9c9155bc',
				'label' => 'Start Time Second',
				'name' => 'tle_start_second',
				'type' => 'number',
				'instructions' => 'A number from 0-59',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff96768979',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effaaac6ab5',
				'label' => 'Start Time Millisecond',
				'name' => 'tle_start_millisecond',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff96768979',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_561a480663443',
				'label' => 'Specify End Date?',
				'name' => 'tle_specify_end_date',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_561a469850cb4',
				'label' => 'End Date',
				'name' => 'tle_end_date',
				'type' => 'date_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_561a480663443',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_55eff9de155bd',
				'label' => 'Specify End Time?',
				'name' => 'tle_specify_end_time',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_561a480663443',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55effa0a155be',
				'label' => 'End Time Hour',
				'name' => 'tle_end_hour',
				'type' => 'number',
				'instructions' => 'A number from 0-23',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff9de155bd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effa25155bf',
				'label' => 'End Time Minute',
				'name' => 'tle_end_minute',
				'type' => 'number',
				'instructions' => 'A number from 0-59',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff9de155bd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effa54c6ab3',
				'label' => 'End Time Second',
				'name' => 'tle_end_second',
				'type' => 'number',
				'instructions' => 'A number from 0-59',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff9de155bd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effb6046b73',
				'label' => 'End Time Millisecond',
				'name' => 'tle_end_millisecond',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff9de155bd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55effb1d07bf9',
				'label' => 'Display Date',
				'name' => 'tle_display_date',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55effb2407bfa',
				'label' => 'Group',
				'name' => 'tle_group',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55effb3007bfb',
				'label' => 'Background Image',
				'name' => 'tle_background_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55effb3f07bfc',
				'label' => 'Background Colour',
				'name' => 'tle_background_colour',
				'type' => 'color_picker',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'timeline-event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_timeline-post-category',
		'title' => 'Timeline Post Category',
		'fields' => array (
			array (
				'key' => 'field_55effc1c59aa4',
				'label' => 'External Media Content',
				'name' => 'tlpc_external_media_content',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55effc2b59aa5',
				'label' => 'Media Image',
				'name' => 'tlpc_media_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55effc3dec309',
				'label' => 'Media Credit',
				'name' => 'tlpc_media_credit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55effc4aec30a',
				'label' => 'Media Caption',
				'name' => 'tlpc_media_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_timeline-settings',
		'title' => 'Timeline Settings',
		'fields' => array (
			array (
				'key' => 'field_55eff652e0650',
				'label' => 'Display Post Categories inline with your theme?',
				'name' => 'display_post_categories_as_inline_timeline',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55eff674e0651',
				'label' => 'Display Post Categories as a Timeline?',
				'name' => 'display_post_categories_as_a_timeline',
				'type' => 'radio',
				'choices' => array (
					'none' => 'None',
					'all' => 'All Categories',
					'specific' => 'Specific Categories',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55eff6a8e0652',
				'label' => 'Only display other Timeline Enabled Categories in Category Hot Swap Menu?',
				'name' => 'only_display_other_timeline_hotswap',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff674e0651',
							'operator' => '==',
							'value' => 'all',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55eff6f9e0653',
				'label' => 'Display only these Post Categories as a Timeline',
				'name' => 'display_only_these_post_categories_as_a_timeline',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55eff674e0651',
							'operator' => '==',
							'value' => 'specific',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'category',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}



?>