<?php

/**
 * override the default from-address in emails generated by wp
 * @see /wp-includes/pluggable.php -> wp_mail() for details
 * fallback-values to check there: $from_name,$from_email
 */
/**
 * override default email-address generated by wp
 */
function mlublogs_mail_from($original_addr) {
        $wp_site = strtolower($_SERVER['SERVER_NAME']);
        if(strpos('www.',$wp_site)===0) {
                $wp_site=substr($wp_site,4);
        }
        $wp_sender='wordpress';
        
        
        if($original_addr=="$wp_sender@$wp_site") {
                $newaddr=(function_exists('is_multisite') && is_multisite())?
                $admin_email = get_site_option( 'admin_email' ):
                $admin_email = get_option('admin_email'); 
        } else {
                $newaddr=$original_addr;
        }
        if(WP_DEBUG) {
                static $calls=0;
                $calls++;
                header("x-mailmapping$calls: #$original_addr#$newaddr");
        }
        return $newaddr;
}
add_filter( 'wp_mail_from', 'mlublogs_mail_from' );
/**
 * override default from-name generated by wp
 */
function mlublogs_mail_fromname($original_name) {
        $wp_fromname='WordPress';
        if(!$original_name||$original_name==$wp_fromname) {
                $new_name='blogs@mlu';
        } else {
                $new_name=$original_name;
        }
        if(WP_DEBUG) {
                static $calls=0;
                $calls++;
                header("x-mail-name$calls: #$original_name#$new_name");
        }
        return $new_name;
}
add_filter( 'wp_mail_from_name','mlublogs_mail_fromname');

# remove colliding cets-filter which overrrides everything by the site-name
remove_filter ('wp_mail_from_name', 'cets_nbd_from_name');

