<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="teaser-content">
        <div class="row">
            <div class="col-xs-12">
                <?php if ($this->isDefault() || defined('AAM_CONTENT_TEASER')) {  ?>
                    <?php echo apply_filters('aam-teaser-ui-filter', AAM_Backend_View::getInstance()->loadPartial('teaser.phtml')); ?>
                <?php } ?>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <?php if ($this->isDefault() || defined('AAM_CONTENT_TEASER')) {  ?>
                    <div>
                        <div class="form-group">
                            <label><?php echo __('Teaser Message', AAM_KEY); ?></label>
                            <textarea class="form-control" name="frontend.teaser.message" rows="3" placeholder="<?php echo __('Enter teaser message...', AAM_KEY); ?>"><?php echo stripslashes($this->getOption('frontend.teaser.message')); ?></textarea>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="frontend.teaser.excerpt"  value="1" <?php echo intval($this->getOption('frontend.teaser.excerpt')) ? 'checked' : ''; ?> />
                                <?php echo __('Add excerpt before teaser message', AAM_KEY); ?>
                            </label>
                        </div>
                    </div>
                <?php } else { ?>
                    <p class="aam-notification">
                        <?php echo AAM_Backend_View_Helper::preparePhrase('You are allowed to setup only the [default] teaser message for all users, roles and visitor. With [AAM Teaser] extension you can customize the teaser message for any user, role or visitors.', 'b', 'b'); ?>
                    </p>
                <?php } ?>
            </div>
        </div>
    </div>
<?php }