<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="utilities-content">
        <table class="table table-striped table-bordered">
            <tbody>
                <?php do_action('aam-pre-utilities-setting'); ?>
                
                <?php foreach($this->getUtilityOptionList() as $id => $option) { ?>
                    <tr>
                        <td>
                            <span class='aam-setting-title'><?php echo $option['title']; ?></span>
                            <p class="aam-setting-description">
                                <?php echo $option['descr']; ?>
                            </p>
                        </td>
                        <td class="text-center">
                            <input type="checkbox" name="<?php echo $id; ?>" id="utility-<?php echo $id; ?>" <?php echo ($option['value'] ? 'checked' : ''); ?> /> <label for="utility-<?php echo $id; ?>"></label>
                        </td>
                    </tr>
                <?php } ?>
                    
                <?php do_action('aam-post-utilities-setting'); ?>

                <tr><td colspan="2"></td></tr>
                <tr>
                    <td>
                        <span class='aam-setting-title'><?php echo __('Clear Cache', AAM_KEY); ?></span>
                        <p class="aam-setting-description">
                            <?php echo __('Clear all AAM cache.', AAM_KEY); ?>
                        </p>
                    </td>
                    <td>
                        <a href="#" class="btn btn-warning btn-block" id="clear-cache">Clear</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class='aam-setting-title'><?php echo __('Clear All Settings', AAM_KEY); ?></span>
                        <p class="aam-setting-description">
                            <?php echo __('Remove all the settings related to AAM (including all extension licenses).', AAM_KEY); ?>
                        </p>
                    </td>
                    <td>
                        <a href="#clear-settings-modal" data-toggle="modal" class="btn btn-danger btn-block">Clear</a>
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="modal fade" id="clear-settings-modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title"><?php echo __('Clear all settings', AAM_KEY); ?></h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center alert alert-danger text-larger"><?php echo __('All AAM settings will be removed.', AAM_KEY); ?></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" id="clear-settings"><?php echo __('Clear', AAM_KEY); ?></button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Cancel', AAM_KEY); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }